import hero from '/assets/images/hero.jpeg';

export const heroImg = hero;

import hmv from '/assets/videos/hero.mp4';
import smallmv from '/assets/videos/smallHero.mp4';
import highlightFirstmv from '/assets/videos/highlight-first.mp4';
import highlightSectmv from '/assets/videos/hightlight-third.mp4';
import highlightThirdmv from '/assets/videos/hightlight-sec.mp4';
import highlightFourthmv from '/assets/videos/hightlight-fourth.mp4';
import exploremv from '/assets/videos/explore.mp4';
import framemv from '/assets/videos/frame.mp4';

import perseus from '/assets/images/perseus.svg';
import perseusWhite from '/assets/images/perseus-white.png';
import apple from '/assets/images/apple.svg';
import watch from '/assets/images/watch.svg';
import right from '/assets/images/right.svg';
import replay from '/assets/images/replay.svg';
import play from '/assets/images/play.svg';
import pause from '/assets/images/pause.svg';

import yellow from '/assets/images/yellow.jpg';
import blue from '/assets/images/blue.jpg';
import white from '/assets/images/white.jpg';
import black from '/assets/images/black.jpg';
import study1 from '/assets/images/study1.jpg';
import study2 from '/assets/images/study2.jpg';
import taurus1 from '/assets/images/taurus1.jpeg';
import taurus2 from '/assets/images/taurus2.jpeg';
import genesis1 from '/assets/images/genesis1.jpg';
import kengo1 from '/assets/images/kengo1.jpg';
import kengo2 from '/assets/images/kengo2.jpg';
import kengo3 from '/assets/images/kengo3.jpg';
import kengo4 from '/assets/images/kengo4.jpg';
import CFR1 from '/assets/images/CFR1.jpg';
import CFR2 from '/assets/images/CFR2.jpg';
import CFR3 from '/assets/images/CFR3.jpg';
import chip from '/assets/images/chip.jpeg';
import frame from '/assets/images/frame.png';
import videography from '/assets/images/videography.svg';
import socialMediaManagement from '/assets/images/socialmediamanagement.svg';
import branding from '/assets/images/branding.svg';
import photo from '/assets/images/photo.svg';
import webDesign from '/assets/images/webdesign.svg';
import contentCreation from '/assets/images/contentcreation.svg';

export const heroVideo = hmv;
export const smallHeroVideo = smallmv;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFourthVideo = highlightFourthmv;
export const exploreVideo = exploremv;
export const frameVideo = framemv;

export const perseusImg = perseus;
export const perseusWhiteImg = perseusWhite;
export const appleImg = apple;
export const watchImg = watch;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const taurus1Img = taurus1;
export const taurus2Img = taurus2;
export const study1Img = study1;
export const study2Img = study2;
export const genesis1Img = genesis1;
export const kengo1Img = kengo1;
export const kengo2Img = kengo2;
export const kengo3Img = kengo3;
export const kengo4Img = kengo4;
export const CFR1Img = CFR1;
export const CFR2Img = CFR2;
export const CFR3Img = CFR3;
export const videographyImg = videography;
export const socialMediaManagementImg = socialMediaManagement;
export const brandingImg = branding;
export const photoImg = photo;
export const webDesignImg = webDesign;
export const contentCreationImg = contentCreation;

export const chipImg = chip;
export const frameImg = frame;
